services:
  - type: web
    name: byods-webhook-server
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: WEBEX_INTEGRATION_CLIENT_ID
        sync: false
      - key: WEBEX_INTEGRATION_CLIENT_SECRET
        sync: false
      - key: WEBEX_SA_CLIENT_ID
        sync: false
      - key: WEBEX_SA_CLIENT_SECRET
        sync: false
      - key: WEBEX_INTEGRATION_REFRESH_TOKEN
        sync: false
